version: '2'
services:
  app:
    image: golf-bag-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=golfbag
